tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk

  - name: terraform
    before: |
      ./bin/terraform.sh

  - name: utils
    before: |
      sudo apt-get install tree

  # https://docs.aws.amazon.com/powershell/latest/userguide/pstools-getting-set-up-linux-mac.html
  # https://docs.aws.amazon.com/powershell/latest/reference/
  - name: powershell
    before: |
      .bin/powershell_cli.sh
    # pwsh
    # Install-Module -Name AWS.Tools.Installer
    # Install-AWSToolsModule AWS.Tools.S3 -CleanUp

  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli.sh
